#!/bin/bash

# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# Copyright (C) 2013 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_SAMBA_CONFIG=${OMV_SAMBA_CONFIG:-"/etc/samba/smb.conf"}

POOL_DIR="/media/"

echo "#======== aufs pool(s) ========" >> ${OMV_SAMBA_CONFIG}

count=$(omv_config_get_count "//services/aufs/share")
index=0

while [ ${index} -le ${count} ]; do
    share=$(omv_config_get "//services/aufs/share[position()=${index}]/smbsharename")
    guestok=$(omv_config_get "//services/aufs/share[position()=${index}]/guestok")
    readonly=$(omv_config_get "//services/aufs/share[position()=${index}]/readonly")
    browseable=$(omv_config_get "//services/aufs/share[position()=${index}]/browseable")

    if [ "${guestok}" == 1 ]; then
        guestok="yes"
    else
        guestok="no"
    fi

    if [ "${readonly}" == 1 ]; then
        readonly="yes"
    else
        readonly="no"
    fi

    if [ "${browseable}" == 1 ]; then
        browseable="yes"
    else
        browseable="no"
    fi

    if [ "${share}" != "" ]; then
        cat <<EOF >> ${OMV_SAMBA_CONFIG}
[${share}]
comment = ${share}
path = ${POOL_DIR}${share}
wide links = yes
guest ok = ${guestok}
readonly = ${readonly}
browseable = ${browseable}
EOF
    fi

    index=$(( ${index} + 1 ))
done;
